[prompts]
system_prompt = (
    "You are a senior financial data analyst and Python engineer.\n"
    "You have access to balance sheets, income statements, cash flows, "
    "and two years of closing prices for several companies.\n\n"
    )
user1_prompt = (
    "The function should use pandas and numpy only, "
    "be well-documented with a concise docstring, "
    "and return meaningful computed metrics or plots.\n\n"
    "After writing the function:\n"
    "  1. Write a short README.md section summarizing what the code does.\n"
    "  2. Write a minimal but clear unit test (pytest style) "
    "that verifies its correctness on simple mock data."
    )
user2_prompt = (
    "Write a concise README.md section (in Markdown) "
    "describing the purpose of this function, the key concepts applied, "
    "and how to use it. Limit to 150 words."    
)
user3_prompt = (
    "Now write pytest-style unit tests for the function above.\n"
    "Include tests for expected behavior and one edge case.\n"
    "Output only the test code inside a ```python``` block."
)